rootProject.name = "ComposeCookBook"
include(":app")
include(":demos:instagram")
include(":data")
include(":theme")
include(":demos:cryptoapp")
include(":demos:cryptoapp-data")
include(":components:charts")
include(":components:tags")
include(":components:carousel")
include(":demos:moviesapp:data")
include(":demos:moviesapp:app")
