rootProject.name = "ComposeCookBook"
include(":app")
include(":demos:instagram")
include(":data")
include(":theme")
include(":demos:cryptoapp:app")
include(":demos:cryptoapp:data")
include(":demos:moviesapp:app")
include(":demos:moviesapp:data")
include(":components:charts")
include(":components:tags")
include(":components:carousel")
include(":components:verticalgrid")
include(":demos:spotify")
include(":demos:twitter")
include(":demos:youtube")
